In [71]:
import pandas as pd

# Exemplo: carregando um dos arquivos
df_data = pd.read_pickle('C:/Users/caioc/OneDrive/Documentos/GitHub/mvp-data-analyst-global-ai-market/source/job_data_cache.pkl')
df_id = pd.read_pickle('C:/Users/caioc/OneDrive/Documentos/GitHub/mvp-data-analyst-global-ai-market/source/job_ids_cache.pkl')

In [74]:
df_data

# Converter valores do dict em lista de dicionários
lista_registros = list(df_data.values())

# Criar o DataFrame
df = pd.DataFrame(lista_registros)

df.to_excel('source/job_data_cache.xlsx', index=False)

In [ ]:
df = df.drop(columns=['job_title', 'time_posted', 'num_applicants'])

In [67]:
df.to_excel('source/job_data_cache.xlsx', index=False)
df.to_csv('source/job_data.csv', index=False, sep=';', encoding='utf-8')

In [68]:
df = pd.read_excel('source/job_data_cache.xlsx')

In [ ]:
dict_skills = {
    'Aws': ['Aws'],
    'Azure': ['Azure'],
    'Computer Vision': ['Computer Vision', 'Visão Computacional'],
    'Data Visualization': ['Data Visualization', 'Dashboard', 'Visualização de Dados'],
    'Deep Learning': ['Deep Learning', 'Aprendizagem profunda'],
    'Docker': ['Docker'],
    'Gcp': ['Gcp', 'Google Cloud', 'Google Cloud Plataform'],
    'Git': ['Git', 'Github'],
    'Hadoop': ['Hadoop'],
    'Java': ['Java'],
    'Kubernetes': ['Kubernetes'],
    'Linux': ['Linux'],
    'Mathematics': ['Mathematics', 'Matematica', 'Matemática', 'reas correlatas'],
    'Mlops': ['Mlops'],
    'Nlp': ['Nlp'],
    'Python': ['Python', 'Rython', 'ython'],
    'Pytorch': ['Pytorch'],
    'R': ['Linguagem R'],
    'Scala': ['Scala'],
    'Spark': ['Spark', 'Pyspark'],
    'Sql': ['Sql'],
    'Statistics': ['Statistics', 'Estatistica', 'Estatística', 'reas correlatas'],
    'Tableau': ['Tableau'],
    'Tensorflow': ['Tensorflow']
}

import re

def encontrar_skills_aperfeicoado(texto):
    skills_encontradas = []
    texto_lower = texto.lower()
    for skill_padrao, variacoes in dict_skills.items():
        for variacao in variacoes:
            # Se for a linguagem R, usa regex pra procurar palavra isolada
            if skill_padrao == 'R':
                if re.search(r'\b[rR]\b', texto):  # case-insensitive p/ R isolado
                    skills_encontradas.append(skill_padrao)
                    break
            else:
                if variacao.lower() in texto_lower:
                    skills_encontradas.append(skill_padrao)
                    break
    return list(set(skills_encontradas))

In [70]:
df['required_skills'] = df['job_description'].apply(encontrar_skills_aperfeicoado)
df

,job_id,work_model,keyword,scrape_date,company_name,location,xp_level,job_type,job_sectors,job_description,required_skills
0,4219203458,Presencial,Analista de Dados,19-05-2025 07:56:44,Cielo,"Barueri, SP",Assistente,Tempo integral,Atividades de serviços financeiros,"Job Description\nSomos mais que uma máquina, s...","[Mathematics, Sql, Statistics]"
1,4229491792,Presencial,Analista de Dados,19-05-2025 07:56:44,SulAmérica,"São Paulo, SP",Pleno-sênior,Tempo integral,Seguros e previdência complementar e Serviços ...,A SulAmérica há mais de 125 anos se dedica a e...,"[Python, R, Mathematics, Sql, Statistics, Data..."
2,4209520797,Presencial,Analista de Dados,19-05-2025 07:56:44,Banco Fibra,"São Paulo, SP",Não aplicável,Tempo integral,Bancos,Somos um Banco que trabalha na busca do melhor...,[Python]
3,4201072662,Presencial,Analista de Dados,19-05-2025 07:56:44,Capco,"São Paulo, SP",Pleno-sênior,Tempo integral,Atividades de serviços financeiros,SOBRE A CAPCO\nA Capco é uma consultoria globa...,"[Python, R, Git, Spark, Hadoop, Azure, Sql, Sc..."
4,4223039814,Presencial,Analista de Dados,19-05-2025 07:56:44,C6 Bank,"São Paulo, SP",Assistente,Tempo integral,Bancos,Nossa área de Processos & Controles\nA área de...,"[Sql, Python, Data Visualization, Tableau]"
...,...,...,...,...,...,...,...,...,...,...,...
11468,4254545779,Presencial,Analista de BI,22-06-2025 18:00:24,Netvagas,"Barueri, SP",Pleno-sênior,Tempo integral,Fornecimento e gestão de recursos humanos,QUER INICIAR SUA CARREIRA AUTOMATIZANDO PROCES...,"[Mathematics, Sql, Statistics, Python]"
11469,4254499275,Presencial,Analista de BI,22-06-2025 18:00:24,Netvagas,"Balneário Camboriú, SC",Pleno-sênior,Tempo integral,Fornecimento e gestão de recursos humanos,Analista de BI Sênior para atuar em uma indúst...,"[Data Visualization, Python, Mathematics, Sql,..."
11470,4254284742,Híbrido,Analista de BI,22-06-2025 18:00:24,Netvagas,"São Paulo, SP",Pleno-sênior,Tempo integral,Fornecimento e gestão de recursos humanos,"Ei, você já pensou em entrar na empolgante áre...","[Sql, Data Visualization, Tableau]"
11471,4254727174,Remoto,Machine Learning Engineer,22-06-2025 18:00:24,micro1,Brasil,Pleno-sênior,Contrato,Desenvolvimento de software e Atividades dos s...,Job Title:\nMachine Learning Engineer\nJob Typ...,"[Computer Vision, Python, Spark, Deep Learning..."
11472,4254499244,Presencial,AI Engineer,22-06-2025 18:00:24,Netvagas,"São José dos Campos, SP",Assistente,Tempo integral,Fornecimento e gestão de recursos humanos,"Somos uma EdTech brasileira, desenvolvemos pro...","[Python, Nlp]"

In [51]:
print(df1.loc[df1['job_id'] == 4254727174	, 'required_skills'].values[0])

['Computer Vision', 'Python', 'Spark', 'Deep Learning', 'Scala', 'Nlp']

In [75]:
file_path_github = r"https://raw.githubusercontent.com/Cavalheiro93/mvp-data-analyst-global-ai-market/refs/heads/main/source/ai_job_dataset.csv"
file_path_brasil = r'https://raw.githubusercontent.com/Cavalheiro93/mvp-data-analyst-global-ai-market/main/source/job_data_cache.xlsx'

df_global = pd.read_csv(file_path_github, sep=',', encoding='latin1')
df_brasil = pd.read_excel(file_path_brasil)

In [77]:
df_global.head(5)

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [78]:
df_brasil.head(5)

,job_id,work_model,keyword,scrape_date,job_title,company_name,location,time_posted,num_applicants,xp_level,job_type,job_sectors,job_description
0,4219203458,Presencial,Analista de Dados,19-05-2025 07:56:44,Analista de Dados e Serviço ao Cliente Junior,Cielo,"Barueri, SP",Há 2 semanas,144 candidaturas,Assistente,Tempo integral,Atividades de serviços financeiros,"Job Description\nSomos mais que uma máquina, s..."
1,4229491792,Presencial,Analista de Dados,19-05-2025 07:56:44,Analista de dados de negócios,SulAmérica,"São Paulo, SP",Há 2 dias,189 candidaturas,Pleno-sênior,Tempo integral,Seguros e previdência complementar e Serviços ...,A SulAmérica há mais de 125 anos se dedica a e...
2,4209520797,Presencial,Analista de Dados,19-05-2025 07:56:44,Analista de Dados Júnior,Banco Fibra,"São Paulo, SP",Há 1 mês,126 candidaturas,Não aplicável,Tempo integral,Bancos,Somos um Banco que trabalha na busca do melhor...
3,4201072662,Presencial,Analista de Dados,19-05-2025 07:56:44,"Analista de Dados - Júnior, Pleno e Sênior | R...",Capco,"São Paulo, SP",Há 23 horas,189 candidaturas,Pleno-sênior,Tempo integral,Atividades de serviços financeiros,SOBRE A CAPCO\nA Capco é uma consultoria globa...
4,4223039814,Presencial,Analista de Dados,19-05-2025 07:56:44,Analista de Dados & Analytics Pleno | Riscos e...,C6 Bank,"São Paulo, SP",Há 1 semana,63 candidaturas,Assistente,Tempo integral,Bancos,Nossa área de Processos & Controles\nA área de...

In [79]:
df_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

In [80]:
df_brasil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11473 entries, 0 to 11472
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           11473 non-null  int64
 1   work_model       11473 non-null  object
 2   keyword          11473 non-null  object
 3   scrape_date      11473 non-null  object
 4   job_title        11473 non-null  object
 5   company_name     11473 non-null  object
 6   location         11473 non-null  object
 7   time_posted      11473 non-null  object
 8   num_applicants   2178 non-null   object
 9   xp_level         11473 non-null  object
 10  job_type         11473 non-null  object
 11  job_sectors      11411 non-null  object
 12  job_description  11473 non-null  object
dtypes: int64(1), object(12)
memory usage: 1.1+ MB